apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/jdht1992/eks-gateway-api.git"
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-demo-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
